"""Проверка миграций туда-обратно и расхождения моделей с миграциями.

Тесты синхронные: Alembic запускает собственный event loop.
"""

import asyncio

from alembic import command
from sqlalchemy import inspect
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import create_async_engine

from tests.conftest import make_alembic_config


def _table_names(connection: Connection) -> set[str]:
    return set(inspect(connection).get_table_names())


async def _tables(database_url: str) -> set[str]:
    engine = create_async_engine(database_url)
    try:
        async with engine.connect() as conn:
            return await conn.run_sync(_table_names)
    finally:
        await engine.dispose()


def test_migrations_downgrade_and_upgrade(test_database_url: str) -> None:
    config = make_alembic_config(test_database_url)

    command.downgrade(config, "base")
    assert asyncio.run(_tables(test_database_url)) == {"alembic_version"}

    command.upgrade(config, "head")
    assert asyncio.run(_tables(test_database_url)) == {"alembic_version", "users", "projects"}


def test_models_match_migrations(test_database_url: str) -> None:
    # Бросает AutogenerateDiffsDetected, если модели и миграции расходятся.
    command.check(make_alembic_config(test_database_url))
